Implement session expiry in backend
aalto-grades/base-repository pull request #140
Opened 2023-02-02 16:22 UTC by Gskartwii

Closes #122.
Closes #105.

2023-02-02 16:44 UTC, no-comma reviewed
Looks good, though I wonder, is there a particular reason to have 25 hours as the expiry time? Should it maybe be configurable somehow instead?

2023-02-02 16:48 UTC, Gskartwii commented
Good question about the hardcoded expiry time. It could be more clear to separate it into a clearly marked constant - or would you even feel it could deserve a new environment variable?

2023-02-02 16:51 UTC, jj-stigell requested changes

2023-02-02 16:51 UTC, jj-stigell commented on server/src/routes/login.ts
> +              expiresIn: '25h',
Would it be better to set the `expiresIn` at `configs/config.ts`, now any changes must be applied to multiple places (here and tests)

2023-02-02 16:58 UTC, no-comma commented
> Good question about the hardcoded expiry time. It could be more clear to separate it into a clearly marked constant - or would you even feel it could deserve a new environment variable?

Defining it as a constant in the code would be good enough now I think. I see nothing immediately wrong with 25 hours, just wondering if it has some special significance (e.g. standard session expiry time in multiple services).

2023-02-06 11:02 UTC, jj-stigell approved these changes

2023-02-06 11:12 UTC, no-comma approved these changes

2023-02-06 11:12 UTC, merged