Update sisu routes
aalto-grades/base-repository pull request #142
Opened 2023-02-07 09:38 UTC by jj-stigell

Changes to the Sisu instance routes
* Updated sisu routes to match the new API spec.
* Added new attribute `sisuInstanceId` to the `courseInstance` model, this should prevent any situations where our internal id's get mixed up with sisu instance id's. Value is unique and nullable (incase instance does not exist in sisu but we anyway want to add it into aalto-grades) 
* Added new mock data and updated tests to handle `sisuInstanceId`.
* Naming of parameters changed to more self-explanatory. `instanceId` => `sisuInstanceId`, etc.

2023-02-11 20:06 UTC, no-comma requested changes
Good changes so far, but there are a couple more things that could be done in this PR.

This doesn't completely match our spec just yet. On success the controllers should respond with
```
{
  success: true,
  data: {
    courseInstances: ...
  }
}
```
and in failures they should use the 502 status and return an error message `external API error: ${sisuStatusCode}`.

Also I think that rather than referring to "Sisu instances" it would be better to be explicit by talking about "Sisu course instances" instead, so `sisuCourseInstanceId` etc.

2023-02-12 08:51 UTC, jj-stigell commented on server/src/controllers/course.ts
> +    .string(),
added `.notRequired()`, wrapped the return data to `data` object. renamed  `sisuInstance` to `sisuCourseInstance`. I would add the error message and status code after we get the custom error types and middleware ready.

2023-02-12 13:31 UTC, no-comma commented on server/src/controllers/course.ts
> +    .string(),
Fair enough.

2023-02-12 13:31 UTC, no-comma approved these changes

2023-02-13 08:12 UTC, Gskartwii reviewed
Nice, just wanted to verify a minor detail before merging this.

2023-02-13 08:12 UTC, Gskartwii commented on server/src/controllers/course.ts
> -  id?: number | undefined,
Just to ensure I understand, this is still meant to be optional, but the `| undefined` is being removed due to redundancy?

2023-02-13 08:15 UTC, Gskartwii commented on server/src/controllers/course.ts
> -  id?: number | undefined,
Resolved, thanks @no-comma

2023-02-13 08:15 UTC, Gskartwii approved these changes

2023-02-13 08:15 UTC, merged