Create client side assignment mock data
aalto-grades/base-repository pull request #164
Opened 2023-02-24 08:37 UTC by viivi-uhari

Create client side assignment mock data to use on the client side (`mockAssignmentsClient.js`), and mock data of the format that may be gotten from the server side (`mockAssignmentsServer.js`). Fix accordions to match the format of `mockAssignmentsClient.js`.

2023-02-24 12:18 UTC, kiiamakir approved these changes
Looks great!

2023-02-27 09:37 UTC, marillam requested changes
Looks very good, great job!

2023-02-27 09:37 UTC, marillam commented on client/src/services/formulas.js
> +  const formula = mockFormulas.find( formula => formula.id === formulaId);
Space before last )? Not mandatory change imo

2023-02-27 09:37 UTC, marillam commented on client/src/components/assignments/AssignmentCategory.js
> +        : <></>
If no alternative (just <></>) then maybe 
{ subAssignments.length !== 0 &&
    Component here
}

2023-02-27 09:37 UTC, marillam commented on client/src/components/assignments/Accordion.js
> +      }
Switch syntax here?
{ formulaId &&
Component
}

2023-02-27 10:16 UTC, marillam approved these changes

2023-02-27 10:18 UTC, merged