Ids and some classNames to ease navigation in tests
aalto-grades/base-repository pull request #192
Opened 2023-04-16 07:45 UTC by marillam

Added ids and classNames when there were many options without clear separating id.

Please comment if need for more naming

2023-04-16 08:58 UTC, no-comma approved these changes
LGTM

2023-04-19 13:36 UTC, kiiamakir requested changes
Looks good! A few comments about line length

2023-04-19 13:36 UTC, kiiamakir commented on client/src/components/InstanceSummaryView.js
> +        <Button id='ag_create_instance_btn' variant='contained' onClick={() => onCreateInstance()} disabled={messageInfo?.severity === 'info'}>Create instance</Button>
Should separate these onto individual rows to make the line length a bit shorter

2023-04-19 13:36 UTC, kiiamakir commented on client/src/components/course-view/Assignments.js
> +          <Button id='ag_course_results_btn' variant='outlined' onClick={() => navigate(`/${courseId}/course-results/${instance.id}`)}>See course results</Button>
Here as well

2023-04-20 04:39 UTC, lakooi approved these changes

2023-04-20 11:33 UTC, kiiamakir approved these changes

2023-04-20 11:33 UTC, merged