Docker compose development setup
aalto-grades/base-repository pull request #43
Opened 2022-11-23 11:52 UTC by Gskartwii

2022-11-23 14:53 UTC, no-comma requested changes
The docker files seem good, just some README style comments.

2022-11-23 14:53 UTC, no-comma commented on README.md
> +You can run the development build of the software by running "docker-compose" up in the root folder of the project.
> "docker-compose" up

This could be in an inline code block instead like so: `docker-compose up`

2022-11-23 14:53 UTC, no-comma commented on README.md
> +This command has one requirement which is defining the environmental variable "POSTGRES_PASSWORD" before execution.
> "POSTGRES_PASSWORD"

This could also be in an inline code block.

2022-11-23 14:53 UTC, no-comma commented on README.md
> +    docker-compose up
The leading spaces could be removed and `$` added in front of each command:
```
$ export POSTGRES_PASSWORD=XXXX
$ docker-compose up
```

2022-11-23 14:55 UTC, no-comma commented on README.md
> +# Development build
Use `##` instea

2022-11-28 13:50 UTC, no-comma approved these changes

2022-12-01 11:43 UTC, jj-stigell approved these changes

2022-12-01 11:43 UTC, merged